# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /afs/athena.mit.edu/user/i/s/isab8liu/6.111/Labs/lab4/lab4.cache/wt [current_project]
set_property parent.project_path /afs/athena.mit.edu/user/i/s/isab8liu/6.111/Labs/lab4/lab4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  /afs/athena.mit.edu/user/i/s/isab8liu/6.111/Labs/lab4/synchronize.v
  /afs/athena.mit.edu/user/i/s/isab8liu/6.111/Labs/lab4/debounce.v
  /afs/athena.mit.edu/user/i/s/isab8liu/6.111/Labs/lab4/lab4.srcs/sources_1/new/fuel_pump.v
  /afs/athena.mit.edu/user/i/s/isab8liu/6.111/Labs/lab4/lab4.srcs/sources_1/new/anti-theft.v
  /afs/athena.mit.edu/user/i/s/isab8liu/6.111/Labs/lab4/lab4.srcs/sources_1/new/debouncer.v
  /afs/athena.mit.edu/user/i/s/isab8liu/6.111/Labs/lab4/lab4.srcs/sources_1/new/status_light.v
  /afs/athena.mit.edu/user/i/s/isab8liu/6.111/Labs/lab4/lab4.srcs/sources_1/new/divider.v
  /afs/athena.mit.edu/user/i/s/isab8liu/6.111/Labs/lab4/lab4.srcs/sources_1/new/timer.v
  /afs/athena.mit.edu/user/i/s/isab8liu/6.111/Labs/lab4/lab4.srcs/sources_1/new/time_parameters.v
  /afs/athena.mit.edu/user/i/s/isab8liu/6.111/Labs/lab4/lab4.srcs/sources_1/new/siren.v
  /afs/athena.mit.edu/user/i/s/isab8liu/6.111/Labs/lab4/display_8hex.v
  /afs/athena.mit.edu/user/i/s/isab8liu/6.111/Labs/lab4/labkit_lab4.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /afs/athena.mit.edu/user/i/s/isab8liu/6.111/Labs/lab4/Nexys4DDR_Master_lab4.xdc
set_property used_in_implementation false [get_files /afs/athena.mit.edu/user/i/s/isab8liu/6.111/Labs/lab4/Nexys4DDR_Master_lab4.xdc]


synth_design -top labkit -part xc7a100tcsg324-3


write_checkpoint -force -noxdef labkit.dcp

catch { report_utilization -file labkit_utilization_synth.rpt -pb labkit_utilization_synth.pb }
